/**
 * Track and Class definitions.
 * Each class has 5 tracks unlocked progressively (top-2 finish to unlock next).
 */

export const CLASSES = {
  'addition': {
    id: 'addition',
    name: 'Rookie League',
    operation: 'addition',
    operationSymbol: '+',
    emoji: '🟢',
    carType: 'Go-Karts',
    unlockCost: 0,
    color: 0x44cc44,
    bucksMultiplier: 1,
    tracks: [
      'starter-speedway',
      'clover-circuit',
      'sunset-raceway',
      'mountain-pass',
      'thunder-road',
    ],
  },
  'subtraction': {
    id: 'subtraction',
    name: 'Amateur Circuit',
    operation: 'subtraction',
    operationSymbol: '−',
    emoji: '🔵',
    carType: 'Rally Cars',
    unlockCost: 1000,
    color: 0x4488ff,
    bucksMultiplier: 1.5,
    tracks: [
      'dusty-trail',
      'gravel-gulch',
      'mudslide-run',
      'canyon-drift',
      'avalanche-alley',
    ],
  },
  'multiplication': {
    id: 'multiplication',
    name: 'Pro Series',
    operation: 'multiplication',
    operationSymbol: '×',
    emoji: '🟡',
    carType: 'Monster Trucks',
    unlockCost: 5000,
    color: 0xffcc00,
    bucksMultiplier: 2,
    tracks: [
      'crusher-circuit',
      'rumble-road',
      'smash-speedway',
      'demolition-drive',
      'titan-track',
    ],
  },
  'division': {
    id: 'division',
    name: 'Championship',
    operation: 'division',
    operationSymbol: '÷',
    emoji: '🔴',
    carType: 'Formula 1',
    unlockCost: 10000,
    color: 0xff4444,
    bucksMultiplier: 3,
    tracks: [
      'grand-straightaway',
      'precision-curve',
      'apex-run',
      'victory-lane',
      'champions-ring',
    ],
  },
  'advanced': {
    id: 'advanced',
    name: 'Superclass',
    operation: 'advanced',
    operationSymbol: '⚡',
    emoji: '⚡',
    carType: 'Supercars',
    unlockCost: 20000,
    color: 0xcc44ff,
    bucksMultiplier: 4,
    tracks: [
      'power-circuit',
      'root-run',
      'formula-speedway',
      'apex-express',
      'champions-formula',
    ],
  },
};

export const TRACKS = {
  // ── Rookie League (Addition) ───────────────────────────────────────────
  'starter-speedway': {
    id: 'starter-speedway',
    classId: 'addition',
    name: 'Starter Speedway',
    trackIndex: 0,
    description: 'Single + Single  (3+4)',
    fallbackAnswerTimeMs: 5000,
    operandA: { min: 1, max: 9 },
    operandB: { min: 1, max: 9 },
  },
  'clover-circuit': {
    id: 'clover-circuit',
    classId: 'addition',
    name: 'Clover Circuit',
    trackIndex: 1,
    description: 'Double + Single  (25+7)',
    fallbackAnswerTimeMs: 7000,
    operandA: { min: 10, max: 99 },
    operandB: { min: 1, max: 9 },
  },
  'sunset-raceway': {
    id: 'sunset-raceway',
    classId: 'addition',
    name: 'Sunset Raceway',
    trackIndex: 2,
    description: 'Double + Double  (34+28)',
    fallbackAnswerTimeMs: 10000,
    operandA: { min: 10, max: 99 },
    operandB: { min: 10, max: 99 },
  },
  'mountain-pass': {
    id: 'mountain-pass',
    classId: 'addition',
    name: 'Mountain Pass',
    trackIndex: 3,
    description: 'Triple + Double  (142+67)',
    fallbackAnswerTimeMs: 10000,
    operandA: { min: 100, max: 999 },
    operandB: { min: 10, max: 99 },
  },
  'thunder-road': {
    id: 'thunder-road',
    classId: 'addition',
    name: 'Thunder Road',
    trackIndex: 4,
    description: 'Triple + Triple  (385+247)',
    fallbackAnswerTimeMs: 10000,
    operandA: { min: 100, max: 999 },
    operandB: { min: 100, max: 999 },
  },

  // ── Amateur Circuit (Subtraction) ────────────────────────────────────
  'dusty-trail': {
    id: 'dusty-trail',
    classId: 'subtraction',
    name: 'Dusty Trail',
    trackIndex: 0,
    description: 'Single − Single  (8−3)',
    fallbackAnswerTimeMs: 5000,
    operandA: { min: 2, max: 9 },
    operandB: { min: 1, max: 8 },
  },
  'gravel-gulch': {
    id: 'gravel-gulch',
    classId: 'subtraction',
    name: 'Gravel Gulch',
    trackIndex: 1,
    description: 'Double − Single  (45−7)',
    fallbackAnswerTimeMs: 7000,
    operandA: { min: 10, max: 99 },
    operandB: { min: 1, max: 9 },
  },
  'mudslide-run': {
    id: 'mudslide-run',
    classId: 'subtraction',
    name: 'Mudslide Run',
    trackIndex: 2,
    description: 'Double − Double  (73−28)',
    fallbackAnswerTimeMs: 10000,
    operandA: { min: 20, max: 99 },
    operandB: { min: 10, max: 50 },
  },
  'canyon-drift': {
    id: 'canyon-drift',
    classId: 'subtraction',
    name: 'Canyon Drift',
    trackIndex: 3,
    description: 'Triple − Double  (342−67)',
    fallbackAnswerTimeMs: 10000,
    operandA: { min: 100, max: 999 },
    operandB: { min: 10, max: 99 },
  },
  'avalanche-alley': {
    id: 'avalanche-alley',
    classId: 'subtraction',
    name: 'Avalanche Alley',
    trackIndex: 4,
    description: 'Triple − Triple  (501−247)',
    fallbackAnswerTimeMs: 10000,
    operandA: { min: 200, max: 999 },
    operandB: { min: 100, max: 499 },
  },

  // ── Pro Series (Multiplication) ───────────────────────────────────────
  'crusher-circuit': {
    id: 'crusher-circuit',
    classId: 'multiplication',
    name: 'Crusher Circuit',
    trackIndex: 0,
    description: 'Single × Single  (3×4)',
    fallbackAnswerTimeMs: 5000,
    operandA: { min: 2, max: 9 },
    operandB: { min: 2, max: 9 },
  },
  'rumble-road': {
    id: 'rumble-road',
    classId: 'multiplication',
    name: 'Rumble Road',
    trackIndex: 1,
    description: 'Single × Double  (7×12)',
    fallbackAnswerTimeMs: 10000,
    operandA: { min: 2, max: 9 },
    operandB: { min: 10, max: 19 },
  },
  'smash-speedway': {
    id: 'smash-speedway',
    classId: 'multiplication',
    name: 'Smash Speedway',
    trackIndex: 2,
    description: 'Double × Single  (23×6)',
    fallbackAnswerTimeMs: 10000,
    operandA: { min: 10, max: 29 },
    operandB: { min: 2, max: 9 },
  },
  'demolition-drive': {
    id: 'demolition-drive',
    classId: 'multiplication',
    name: 'Demolition Drive',
    trackIndex: 3,
    description: 'Double × Double  (12×15)',
    fallbackAnswerTimeMs: 20000,
    operandA: { min: 10, max: 19 },
    operandB: { min: 10, max: 19 },
  },
  'titan-track': {
    id: 'titan-track',
    classId: 'multiplication',
    name: 'Titan Track',
    trackIndex: 4,
    description: 'Double × Double hard  (34×27)',
    fallbackAnswerTimeMs: 20000,
    operandA: { min: 20, max: 49 },
    operandB: { min: 20, max: 49 },
  },

  // ── Championship (Division) ───────────────────────────────────────────
  'grand-straightaway': {
    id: 'grand-straightaway',
    classId: 'division',
    name: 'Grand Straightaway',
    trackIndex: 0,
    description: 'Simple  (12÷3)',
    fallbackAnswerTimeMs: 5000,
    // dividend = divisor * quotient; divisor range, quotient range
    divisorRange: { min: 2, max: 5 },
    quotientRange: { min: 2, max: 9 },
  },
  'precision-curve': {
    id: 'precision-curve',
    classId: 'division',
    name: 'Precision Curve',
    trackIndex: 1,
    description: 'Even division  (45÷5)',
    fallbackAnswerTimeMs: 10000,
    divisorRange: { min: 3, max: 9 },
    quotientRange: { min: 3, max: 9 },
  },
  'apex-run': {
    id: 'apex-run',
    classId: 'division',
    name: 'Apex Run',
    trackIndex: 2,
    description: 'Double ÷ Single  (84÷7)',
    fallbackAnswerTimeMs: 10000,
    divisorRange: { min: 6, max: 9 },
    quotientRange: { min: 8, max: 15 },
  },
  'victory-lane': {
    id: 'victory-lane',
    classId: 'division',
    name: 'Victory Lane',
    trackIndex: 3,
    description: 'Harder  (144÷12)',
    fallbackAnswerTimeMs: 20000,
    divisorRange: { min: 8, max: 12 },
    quotientRange: { min: 8, max: 15 },
  },
  'champions-ring': {
    id: 'champions-ring',
    classId: 'division',
    name: "Champion's Ring",
    trackIndex: 4,
    description: 'Triple ÷ Double  (936÷24)',
    fallbackAnswerTimeMs: 20000,
    divisorRange: { min: 12, max: 30 },
    quotientRange: { min: 12, max: 40 },
  },

  // ── Superclass (Advanced) ─────────────────────────────────────────────
  'power-circuit': {
    id: 'power-circuit',
    classId: 'advanced',
    name: 'Power Circuit',
    trackIndex: 0,
    description: 'Exponents (3⁴ = 81)',
    subType: 'exponents',
    fallbackAnswerTimeMs: 8000,
    baseRange: { min: 2, max: 9 },
    exponentRange: { min: 2, max: 5 },
  },
  'root-run': {
    id: 'root-run',
    classId: 'advanced',
    name: 'Root Run',
    trackIndex: 1,
    description: 'Square Roots (√81 = 9)',
    subType: 'squareRoots',
    fallbackAnswerTimeMs: 8000,
    rootRange: { min: 2, max: 9 },
  },
  'formula-speedway': {
    id: 'formula-speedway',
    classId: 'advanced',
    name: 'Formula Speedway',
    trackIndex: 2,
    description: 'Order of Ops (2 + 3 × 4)',
    subType: 'orderOfOps',
    fallbackAnswerTimeMs: 12000,
    operandRange: { min: 2, max: 9 },
  },
  'apex-express': {
    id: 'apex-express',
    classId: 'advanced',
    name: 'Apex Express',
    trackIndex: 3,
    description: 'Parentheses ((3+5) × 4)',
    subType: 'orderOfOpsHard',
    fallbackAnswerTimeMs: 15000,
    operandRange: { min: 2, max: 15 },
  },
  'champions-formula': {
    id: 'champions-formula',
    classId: 'advanced',
    name: "Champion's Formula",
    trackIndex: 4,
    description: 'Solve for X (X + 7 = 22)',
    subType: 'solveForX',
    fallbackAnswerTimeMs: 15000,
  },
};

export const DEFAULT_TRACK = TRACKS['starter-speedway'];
export const DEFAULT_CLASS = CLASSES['addition'];
